shadow = false
borders = "outset" 


[colors]

	background = ["#cdf6cd", "454", "magenta"]

	shadow     = ["#222288", "blue"]
	view       = "111"

	primary   = ["white"]
	secondary = "#EEEEEE"
	tertiary  = "#252521"


	title_primary   = ["BLUE", "yellow"] 
	title_secondary = "#ffff55"


	highlight          = "#F88"
	highlight_inactive = "#5555FF"

